### ISSUE TITLE
指令习题答题卡

### ISSUE THREAD

**Issue by ken1987** [redwing-team/vuejs-share#1]
[指令习题](https://github.com/redwing-team/vuejs-share/blob/master/chat/%E6%8C%87%E4%BB%A4%E4%B9%A0%E9%A2%98.md)

**Comment by erbing** [comment]
@wishingtree   @liu99990309   @linvar   welcome!

**Comment by amwyyyy** [comment]
1 BD
2 BC
3 C
4 CDEGHI
5 AC

**Comment by wishingtree** [comment]
1.ABC
2.AB
3.ABC
4.FM
5.C

**Comment by liu99990309** [comment]
1、ABC
2、BC
3、C
4、FM
5、BC

**Comment by linvar** [comment]
C
D
A
CDEGHIJM
B

**Comment by erbing** [comment]
1、AC
2、D
3、CD
4、ABCDEGHIJKLN
5、BCD

(感觉有坑)

**Comment by ken1987** [comment]
## 第一题： ABC

`v-show`  不能像 `v-if` 一样配合  `template` 元素使用 

## 第二题： C

A [看文档](http://cn.vuejs.org/guide/conditional.html#u7EC4_u4EF6_u8B66_u544A)
B 还是[看文档](http://cn.vuejs.org/guide/conditional.html#v-if_vs-_v-show)

>  v-if 也是惰性的：如果在初始渲染时条件为假，则什么也不做——在条件第一次变为真时才开始局部编译（编译会被缓存起来）。
> 
> 相比之下，v-show 简单得多——元素始终被编译并保留，只是简单地基于 CSS 切换。

**v-show 简单得多——元素始终被编译并保留**
**v-show 简单得多——元素始终被编译并保留**
**v-show 简单得多——元素始终被编译并保留**
 重要的说三遍，初始化 `modal.a` 的时候 `modal` 为 `null`，会解析报错

D [看文档](http://cn.vuejs.org/guide/conditional.html#v-else)

> v-else 元素必须立即跟在 v-if 或 v-show 元素的后面——否则它不能被识别。

## 第三题：C

这是一个坑啊，索引是从0开始的。
阈值渲染也是从0开始，[看文档](http://cn.vuejs.org/guide/list.html#u503C_u57DF_v-for)

## 第四题：FM

看文档

## 第五题：BC

A `:class` 注意冒号写法，属性值对应的是js的表达式
D  生成的是`a-1 bc`，注意`bclass`和`cclass`中间没有空格

**Comment by erbing** [comment]
补充一点 第三题： D 选项 item in 3    也是 0 ，1， 2   in 前面是索引，后面是  循环次数

**Comment by ken1987** [comment]
@erbing  那么理解也行得通，但是这种写法前面的是值，不是索引。
阈值最终被编译成值为非负整数的数组了。
题外话，其实传入一个小数，VUE 也可以容错。
看下源码的 v-for 的实现就知道了。

``` js
…
_postProcess (value) {
    if (isArray(value)) {
      return value
    } else if (isPlainObject(value)) {
      // convert plain object to array.
      var keys = Object.keys(value)
      var i = keys.length
      var res = new Array(i)
      var key
      while (i--) {
        key = keys[i]
        res[i] = {
          $key: key,
          $value: value[key]
        }
      }
      return res
    } else {
      if (typeof value === 'number' && !isNaN(value)) {
        value = range(value)
      }
      return value || []
    }
  },
…

function range (n) {
  var i = -1
  var ret = new Array(Math.floor(n))
  while (++i < n) {
    ret[i] = i
  }
  return ret
}
```
